version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      PORT: 3000
      MONGO_USER: root
      MONGO_PWD: example
      MONGO_URL: mongo
      MONGO_PORT: 27017
